### ISSUE TITLE
!skip - vote for skipping the mode/map :enhancement:

### ISSUE THREAD

**Issue by OwlyMan** [Danilo1301/crab-game-server-mod#10]
If half the players use this command, the mode/map they are currently playing will be skipped.

(sorry for asking so many features and also if you can give me some way to contact you it would be great thanks ❤️ )

**Comment by Danilo1301** [comment]
You can add me on discord if you want Danilo#7798

Check if it works for you, or you want something different:
https://github.com/Danilo1301/crab-game-server-mod/releases/tag/v2.5
