### ISSUE TITLE
What Does Punchdamage Do???

### ISSUE THREAD

**Issue by Paxo1z** [Danilo1301/crab-game-server-mod#17]
idk what punchdamage does when i type in "!punchdamage 0" for ak and when i use it i dont really see any diffrence also srry if this isnt a issue or not i don't know

**Comment by Danilo1301** [comment]
It just changes the punch damage based on the ak's damage, so the punch will behave like an ak shot (-30 hp I think). A bomb, for example, gives a little knockback, but 0 damage
