### ISSUE TITLE
how to spin item or !ball?

### ISSUE THREAD

**Issue by iHunter69** [Danilo1301/crab-game-server-mod#2]
how to

**Comment by Danilo1301** [comment]
it was in this old mod https://github.com/Danilo1301/crab-game-mod
and doesnt work anymore after the latest update

**Comment by iHunter69** [comment]
can u make it work again?

**Comment by Danilo1301** [comment]
I can't, because dani changed the way the objects sync (it just doesnt sync anymore) :/
