### ISSUE TITLE
Code compilation error. Same as #12.

### ISSUE THREAD

**Issue by BunnyWalks** [Danilo1301/crab-game-server-mod#28]
Same problem as in #12 . I am trying to compile the code, but the same LNK2038 and LNK4075 errors appear.  Opened .sln by Visual studio 2022, 2019, 2017, but only realized that 2017 is too old. I read (Error on ordered pointer comparison against null ptr or 0) from #19, but I only realized that another version is needed.
It looks like this is a serious problem for people.

Can you please write a version of Visual Studio (Example: 2019 16.11.25) and an idea for a fix. I'm not a professional, so please don't write too hard to understand).

Copy from #12 
Warning: LNK4075 ignoring '/INCREMENTAL' due to '/LTCG' specification CrabGameServerMod C:\Users\jwe66\Documents\crab-
game-server-mod-main\LINK 1
Error: LNK2038 mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in helpers.obj
CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-main\sioclient.lib(sio_socket.obj)
Error: LNK2038 mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug'
in helpers.obj CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-
main\sioclient.lib(sio_socket.obj)
Error: LNK2038 mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in helpers.obj
CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-main\sioclient.lib(sio_client.obj)
Error: LNK2038 mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug'
in helpers.obj CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-main\sioclient.lib(sio_client.obj)
Error: LNK2038 mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in helpers.obj
CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-main\sioclient.lib(sio_packet.obj)
Error: LNK2038 mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug'
in helpers.obj CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-
main\sioclient.lib(sio_packet.obj)
Error: LNK2038 mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in helpers.obj
CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-main\sioclient.lib(sio_client_impl.obj)
Error: LNK2038 mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug'
in helpers.obj CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-
main\sioclient.lib(sio_client_impl.obj)
Warning: LNK4098 defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library CrabGameServerMod
C:\Users\jwe66\Documents\crab-game-server-mod-main\LINK
Warning: LNK4098 defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library CrabGameServerMod
C:\Users\jwe66\Documents\crab-game-server-mod-main\LINK
Error: LNK1319 8 mismatches detected CrabGameServerMod C:\Users\jwe66\Documents\crab-game-server-mod-
main\x64\Debug\CrabGameServerMod.dll

**Comment by Marihuan0** [comment]
Yeah, im getting the same error while trying to complie it 😔

**Comment by Decoder0007** [comment]
you have to update it

Change the project to C/C++17 and rebuild

**Comment by Decoder0007** [comment]
Or download my fork of it which I have updated and fixed issues with perms
