### ISSUE TITLE
Small feature requests

### ISSUE THREAD

**Issue by protochime327** [Danilo1301/crab-game-server-mod#4]
Hello, I'm using this mod to host a 24/7 server. 

I am looking for a kick command and access to player position etc...

Willing to pay. Let me know if this is possible.

**Comment by Danilo1301** [comment]
I think I get what you're saying
But how much would you pay? I can probably finish this in 1-2 days

**Comment by protochime327** [comment]
> I think I get what you're saying But how much would you pay? I can probably finish this in 1-2 days (or maybe today)
> 
> Also, about the players position, how exactly you want to get them? like a command that prints the position in chat?

I'm willing to pay a price per feature. For example: 
- $50-$100 usd for kick command.
- $10 to $20 usd for playerposition
- etc

I don't know how long everything will take you, so you can quote me if that works better.
I believe there's a way to put a bounty on Github? If you know how that'd be best for me.

**Comment by Danilo1301** [comment]
I've never done this before, but you can use https://app.bountysource.com/
You just need to create an issue on github, then go to the site > Bounties > Post bounty, then put the issue link (you will get redirected to the bounty page)

**Comment by Danilo1301** [comment]
> > I think I get what you're saying But how much would you pay? I can probably finish this in 1-2 days (or maybe today)
> > Also, about the players position, how exactly you want to get them? like a command that prints the position in chat?
> 
> I'm willing to pay a price per feature. For example:
> 
> * $50-$100 usd for kick command.
> * $10 to $20 usd for playerposition
> * etc
> 
> In the case of player position, I want to print positions of players in chat so I can learn different coordinates on different maps. That would make teleporting players to spots on the map much easier.
> 
> I don't know how long everything will take you, so you can quote me if that works better. I believe there's a way to put a bounty on Github? If you know how that'd be best for me.

I've never done this before, but you can use https://app.bountysource.com/
You just need to create an issue on github, then go to the site > Bounties > Post bounty, then put the issue link (you will get redirected to the bounty page)

**Comment by protochime327** [comment]
> > > I think I get what you're saying But how much would you pay? I can probably finish this in 1-2 days (or maybe today)
> > > Also, about the players position, how exactly you want to get them? like a command that prints the position in chat?
> > 
> > 
> > I'm willing to pay a price per feature. For example:
> > 
> > * $50-$100 usd for kick command.
> > * $10 to $20 usd for playerposition
> > * etc
> > 
> > In the case of player position, I want to print positions of players in chat so I can learn different coordinates on different maps. That would make teleporting players to spots on the map much easier.
> > I don't know how long everything will take you, so you can quote me if that works better. I believe there's a way to put a bounty on Github? If you know how that'd be best for me.
> 
> I've never done this before, but you can use https://app.bountysource.com/ You just need to create an issue on github, then go to the site > Bounties > Post bounty, then put the issue link (you will get redirected to the bounty page)

Understood. Thank you for the update by the way!
