### ISSUE TITLE
Feature Request: Start Lobby Command / Auto Start [$20]

### ISSUE THREAD

**Issue by protochime327** [Danilo1301/crab-game-server-mod#6]
Would be nice to have a command to start the lobby. This way players don't have to wait for others to ready up.

**Comment by Danilo1301** [comment]
I'll see what I can do
My computer is really slow those days for some reason

**Comment by Danilo1301** [comment]
I added the !start command, and also fixed the help message bug

**Comment by protochime327** [comment]
Could auto start after some time when the lobby is loaded? I'm not always on and don't want to give everyone perms.
I tried myself, but am experiencing some crashes.

Thank you =]

**Comment by Danilo1301** [comment]
https://github.com/Danilo1301/crab-game-server-mod/compare/v1.3.2...v1.3.3

You can type !autostart to enable or disable the autostart
and !autostart [seconds] to change the time
