### ISSUE TITLE
Add Vote-Kick

### ISSUE THREAD

**Issue by OwlyMan** [Danilo1301/crab-game-server-mod#8]
Sorry for opening this in issue, i have no idea how i can contact you.

If you want, could you add a vote-kick/vote-ban system? i really think this mod is useful, i use it sometimes and a lot of players enjoy it.
I would like to host the mod on a machine, but if i go afk, cheaters or people who harass others can't be banned.
The vote-kick would work like this:
/votekick PlayerName Reason
a message will appear in chat with "Player1 wants to kick Player2 for: he's cheating, i saw him flying!" use /yes if you agree.

if half the players agree to kick the player with /yes, he will be kicked.

Again, sorry for proposing this in the "issues" section, Thanks!

**Comment by Danilo1301** [comment]
Github has a few labels such as "enhancement", so its actually the right place

And no problem. I'll see what I can do tomorrow, when I have some time

**Comment by Danilo1301** [comment]
https://github.com/Danilo1301/crab-game-server-mod/releases/tag/v2.3
