### ISSUE TITLE
Option for killing the host when the game starts :enhancement:

### ISSUE THREAD

**Issue by OwlyMan** [Danilo1301/crab-game-server-mod#9]
When the game starts (or in the lobby) for the   host there may be the option where he gets killed after the game starts, so that other players don't have to wait for it In green light / red light cases or other modes.

If the host activates this option, their vote will be automatically put "Ready" each time they return to the waiting lobby

This would also be useful if you want to create lobbies that are open for many hours or even 24/7

(Also thanks for the votekick ❤️ )

**Comment by Danilo1301** [comment]
No problem!
I added the !autodie, it will send you to spectator mode every time you try to spawn
